
# general settings
name: 102_PFT_light_SRx3_finetune_thermal_rgb_tv_30k
model_type: PFTModel
scale: 3
num_gpu: 1
manual_seed: 0

# find_unused_parameters needs to be true, otherwise it will affect performance
find_unused_parameters: true

# dataset and data loader settings
datasets:
  train:
    name: CIDIS_train
    type: PairedImageDatasetRGB
    dataroot_gt: /teamspace/uploads/cidis-dataset/thermal/train_HR_bicubic/X3
    dataroot_lq: /teamspace/uploads/cidis-dataset/thermal/train_LR_bicubic
    dataroot_gt_rgb: /teamspace/uploads/cidis-dataset/visible/train_HR_bicubic/X3
    # filename_tmpl: '{}x3'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: CIDIS_val
    type: PairedImageDatasetRGB
    dataroot_gt: /teamspace/uploads/cidis-dataset/thermal/val_HR_bicubic/X3
    dataroot_lq: /teamspace/uploads/cidis-dataset/thermal/val_LR_bicubic
    dataroot_gt_rgb: /teamspace/uploads/cidis-dataset/visible/val_HR_bicubic/X3
    # filename_tmpl: '{}x3'
    io_backend:
      type: disk

  # val_2:
  #   name: Set14
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/TestDataSR/HR/Set14/x3
  #   dataroot_lq: datasets/TestDataSR/LR/LRBI/Set14/x3
  #   io_backend:
  #     type: disk

  # val_3:
  #   name: BSD100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/TestDataSR/HR/B100/x3
  #   dataroot_lq: datasets/TestDataSR/LR/LRBI/B100/x3
  #   io_backend:
  #     type: disk

  # val_4:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/TestDataSR/HR/Urban100/x3
  #   dataroot_lq: datasets/TestDataSR/LR/LRBI/Urban100/x3
  #   io_backend:
  #     type: disk

  # val_5:
  #   name: Manga109
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/TestDataSR/HR/Manga109/x3
  #   dataroot_lq: datasets/TestDataSR/LR/LRBI/Manga109/x3
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: PFT
  upscale: 3
  in_chans: 3
  img_size: 64
  embed_dim: 52
  depths: [2, 4, 6, 6, 6]
  num_heads: 4
  num_topk: [1024, 1024,
              256, 256, 256, 256,
              128, 128, 128, 128, 128, 128,
              64, 64, 64, 64, 64, 64,
              32, 32, 32, 32, 32, 32]
  window_size: 32
  convffn_kernel_size: 7
  img_range: 1.
  mlp_ratio: 1
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'
  use_checkpoint: false

# path
path:
  pretrain_network_g: experiments/pretrained_models/101_PFT_light_SRx2_scratch.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [15000, 20000]
    gamma: 0.5

  total_iter: 30000
  warmup_iter: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  cross_channel_opt:
    type: CrossChannelLoss
    reduction: mean
  weighted_tv_opt:
    type: WeightedTVLoss
    loss_weight: 0.5
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: yes

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 3
      test_y_channel: yes

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
